### PR TITLE
Fix for ruby 2 6 2

### PR DESCRIPTION
**Pull request by sagotsky**
I fixed things so this compiles in ruby 2.6.2.  Tests pass.  It still works for me in 2.3.3.  The tl;dr of the bug is that `rb_funcall` gets hostile if you tell it you're passing one arg but you actually pass it three.

I fixed a couple other things along the way.  
* rake-compile was missing so I set that up so I could compile.
* Test setup was weird.  It was requiring chipmunk as an external dependency, so I don't think I was testing against my code changes.  I believe that's fixed now.

Also added a note to the readme to say that the project is unmaintained and looking for a maintainer.

Cheers!

### CODE REVIEW

**Comment by beoran** [comment]
I will merge this fully trusting that it works. It can't get worse anyway. Thanks a lot for the fix! Why not become maintainer? You have my blessing already. ;-)

**Comment by sagotsky** [comment]
Gracias!

I don't have sustainable free time for maintaining a project.  This month is an anomaly while I'm waiting to start my next job (hence having time to play with game physics).

**Comment by beoran** [comment]
I see, but if you could manage an upgrade to chipmunk 7, I and many others
would be grateful. :-)

Op di 2 apr. 2019 21:27 schreef Jon Sagotsky <notifications@github.com>:

**Comment by sagotsky** [comment]
Do you have a sense for how far off that is?  If you want to give me privs
we can see how far I get.  No promises though.

**Comment by beoran** [comment]
Just upgrading to 7.0.2 chipmunk will probably be easy enough since it seems to be largely backwards compatible with 6.x. You probably just have to upgrade the vendored version. A bit more work is to then to add the new 7.x functions such as cpBodyNewKinematic in the Ruby API. But still, the new API is limited, so that again should not be too much work. I will invite you to this organisation and give you commit provs, then we can see how far you get.

**Comment by sagotsky** [comment]
Sounds good to me.  Do you have any expectations around code review or
should I just go nuts?

**Comment by beoran** [comment]
All in all this project is a wrapper. So as long as it works correctly, preferably with working specs in the spec folder, the style if the code doesn't matter. So go wild as you say.

**Pull request merged**
